name: Windows

on:
  workflow_call:
    inputs:
      os:
        default: windows-latest
        type: string
        required: false

      python-version:
        default: 3.8
        type: string
        required: false

      pyinstaller-version:
        description: PyInstaller version
        type: string
        required: true

      upload:
        default: false
        type: boolean
        required: false

      ref:
        default: ${{ github.ref }}
        type: string
        required: false

  workflow_dispatch:
    inputs:
      os:
        description: Environment
        default: windows-latest
        type: string
        required: true

      python-version:
        description: Python version
        default: 3.8
        type: string
        required: true

      pyinstaller-version:
        description: PyInstaller version
        default: 5.13.1
        type: string
        required: true

      upload:
        description: Upload
        default: true
        type: boolean
        required: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ github.event.inputs.os || inputs.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{inputs.ref || github.ref}}

      - name: Modify PATH
        run: |
          echo "C:\msys64\usr\bin" >> $env:GITHUB_PATH
          echo "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64" >> $env:GITHUB_PATH

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ github.event.inputs.python-version || inputs.python-version }}

      - name: Run build script
        timeout-minutes: 10
        env:
          LOG_LEVEL: INFO
        shell: cmd
        run: |
            python -m pip install --upgrade pip
            pip install pyinstaller==${{ github.event.inputs.pyinstaller-version || inputs.pyinstaller-version }}
            dir
            pyinstaller main.py --onefile --name pyscanner --distpath dist

      - name: Upload Artifact
        if: github.event.inputs.upload || inputs.upload
        uses: actions/upload-artifact@v3
        with:
          name: pyscanner
          path: dist/
          retention-days: 1
